version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  allow:
    - dependency-type: "all"
  rebase-strategy: "disabled"
  reviewers:
  - "ministryofjustice/laa-claim-for-payment"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: thursday
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  rebase-strategy: "disabled"
  reviewers:
  - "ministryofjustice/laa-claim-for-payment"
