# NB: this is only used for *local development*
# see Dockerfile for deployed version
version: "2.1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fee_calculator

  django:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: 'NOT_A_REAL_SECRET_KEY'
    ports:
      - "8000:8080"
    links:
      - db
    environment:
      ENV: local
      DEBUG: "True"
      DJANGO_SECRET_KEY: 'NOT_A_REAL_SECRET_KEY'
      DB_NAME: fee_calculator
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
