# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvocateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=20)),
                ('is_basic', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OffenceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advocate_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='calculator.AdvocateType')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='calculator.FeeType')),
                ('offence_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='calculator.OffenceClass')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('fee_types', models.ManyToManyField(to='calculator.FeeType')),
            ],
        ),
        migrations.RemoveField(
            model_name='billsubtype',
            name='bill_type',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='bist_bill_sub_type',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='scheme',
        ),
        migrations.DeleteModel(
            name='BillSubType',
        ),
        migrations.DeleteModel(
            name='BillType',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
