# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20161121_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='force_third',
        ),
    ]
