# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_remove_price_third'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='fixed_fee',
            field=models.DecimalField(decimal_places=3, default='0.00', max_digits=10),
            preserve_default=False,
        ),
    ]
