# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 11:48
from __future__ import unicode_literals
from decimal import Decimal

from django.core.management import call_command
from django.db import migrations, models
import django.db.models.deletion


def link_uplifts(apps, _):
    price_cls = apps.get_model('calculator', 'Price')

    if price_cls.objects.all().count():
        call_command('loaddata', 'uplift')
        uplift_cls = apps.get_model('calculator', 'Uplift')

        for uplifted_price in price_cls.objects.filter(uplift_percent=Decimal('20.00')):
            case_uplift = uplift_cls.objects.get(pk=1)
            uplifted_price.uplifts.add(case_uplift)
            uplifted_price.save()


def unlink_uplifts(apps, _):
    price_cls = apps.get_model('calculator', 'Price')

    if price_cls.objects.all().count():
        for uplifted_price in price_cls.objects.filter(uplifts__pk=1):
            uplifted_price.uplift_percent = Decimal('20.00')
            uplifted_price.save()


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_price_fixed_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uplift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_from', models.IntegerField()),
                ('limit_to', models.IntegerField(null=True)),
                ('uplift_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='uplifts',
            field=models.ManyToManyField(to='calculator.Uplift'),
        ),
        migrations.RunPython(
            code=link_uplifts, reverse_code=unlink_uplifts
        ),
        migrations.RemoveField(
            model_name='price',
            name='uplift_percent',
        ),
    ]
