# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_price_fixed_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uplift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_from', models.IntegerField()),
                ('limit_to', models.IntegerField(null=True)),
                ('uplift_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='uplifts',
            field=models.ManyToManyField(to='calculator.Uplift'),
        ),
        migrations.RemoveField(
            model_name='price',
            name='uplift_percent',
        ),
    ]
