# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_auto_20171010_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifier',
            old_name='uplift_percent',
            new_name='modifier_percent',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='uplifts',
            new_name='modifiers',
        ),
    ]
