# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20171010_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_from', models.IntegerField()),
                ('limit_to', models.IntegerField(null=True)),
                ('modifier_percent', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='limit_from',
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='limit_to',
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='modifier_percent',
        ),
        migrations.AddField(
            model_name='modifier',
            name='description',
            field=models.CharField(default='Description', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modifier',
            name='name',
            field=models.CharField(default='Name', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modifiervalue',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='calculator.Modifier'),
        ),
    ]
