# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_remove_scheme_effective_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modifier',
            new_name='ModifierType',
        ),
        migrations.RenameField(
            model_name='modifiervalue',
            old_name='modifier',
            new_name='modifier_type',
        ),
    ]
