# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_auto_20171016_0905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModifierValue',
            new_name='Modifier',
        ),
    ]
