# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0015_modifier_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modifier',
            old_name='modifier_percent',
            new_name='percent_per_unit',
        ),
    ]
