# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0016_auto_20171016_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='fixed_percent',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modifier',
            name='priority',
            field=models.SmallIntegerField(default=0),
        ),
    ]
