# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0017_auto_20171017_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='strict_range',
            field=models.BooleanField(default=False),
        ),
    ]
