# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0019_auto_20171031_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='aggregation',
            field=models.CharField(choices=[('sum', 'Sum'), ('max', 'Max')], default='sum', max_length=20),
        ),
    ]
