# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-12 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0022_auto_20180524_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_type', models.PositiveSmallIntegerField(choices=[(1, 'Advocate'), (2, 'Solicitor')])),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='calculator.Scenario')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='scenariocode',
            unique_together=set([('scenario', 'supplier_type')]),
        ),
    ]
