# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-18 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0023_auto_20180612_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariocode',
            name='supplier_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Advocate Graduated Fee Scheme'), (2, 'Litigator Graduated Fee Scheme')]),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='suty_base_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Advocate Graduated Fee Scheme'), (2, 'Litigator Graduated Fee Scheme')]),
        ),
    ]
