# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-18 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0024_auto_20180618_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenariocode',
            old_name='supplier_type',
            new_name='scheme_type',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='suty_base_type',
            new_name='base_type',
        ),
        migrations.AlterUniqueTogether(
            name='scenariocode',
            unique_together=set([('scenario', 'scheme_type')]),
        ),
    ]
