# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-06 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0025_auto_20180618_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='strict_range',
            field=models.BooleanField(default=False),
        ),
    ]
