# Generated by Django 2.1.3 on 2018-11-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0026_price_strict_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetype',
            name='aggregation',
            field=models.CharField(choices=[('sum', 'Sum'), ('max', 'Max')], default='sum', help_text='Specifies how multiple prices for this fee type will be combined.', max_length=20),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='fixed_percent',
            field=models.DecimalField(decimal_places=2, help_text='Adds this percent to the fee if this modifier is applicable.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='percent_per_unit',
            field=models.DecimalField(decimal_places=2, help_text='Adds this percent to the fee for each unit within the range covered by `limit_from` and `limit_to` if this modifier is applicable.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='priority',
            field=models.SmallIntegerField(default=0, help_text='When applying modifiers to to the value of the fee, those with the lowest value of `priority` will be applied first. A `priority` of 0 will mean that the modifier will only provide an increase on the base fee.'),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='required',
            field=models.BooleanField(default=False, help_text='If `True`, prices with this modifier will not be applicable unless this modifier is applicable.'),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='strict_range',
            field=models.BooleanField(default=False, help_text='If `True`, this modifier will only be applicable if the unit count is >= `limit_from` and <= `limit_to`. If `False`, it will apply as long as the unit count is >= `limit_from`.'),
        ),
        migrations.AlterField(
            model_name='price',
            name='fee_per_unit',
            field=models.DecimalField(decimal_places=5, help_text='Adds this value to the fee for each unit within the range covered by `limit_from` and `limit_to` if this price is applicable.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='price',
            name='fixed_fee',
            field=models.DecimalField(decimal_places=5, help_text='Adds this value to the fee if this price is applicable.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='price',
            name='strict_range',
            field=models.BooleanField(default=False, help_text='If `True`, this price will only be applicable if the unit count is >= `limit_from` and <= `limit_to`. If `False`, it will apply as long as the unit count is >= `limit_from`.'),
        ),
    ]
