# Generated by Django 3.2.15 on 2022-10-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0027_auto_20181122_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='hearing_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='hearing_start_date',
            field=models.DateField(null=True),
        ),
    ]
