# Generated by Django 3.2.16 on 2022-11-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0027_auto_20181122_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='earliest_main_hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
