# Generated by Django 4.2.10 on 2024-08-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0028_scheme_earliest_main_hearing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='london_rates_apply',
            field=models.BooleanField(null=True),
        ),
    ]
