apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: laa-fee-calculator-laa-fee-calculator-dev-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    kubernetes.io/ingress.class: "modsec01"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
  name: laa-fee-calculator
  namespace: laa-fee-calculator-dev
spec:
  rules:
    - host: dev.laa-fee-calculator.service.justice.gov.uk
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: laa-fee-calculator
              port:
                number: 8080
  tls:
    - hosts:
      - dev.laa-fee-calculator.service.justice.gov.uk
      secretName: laa-fee-calculator-dev-cert
